access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVVVJRCI6IjJkNzViNTg5LWQ0YWYtNGQ3MS1hY2FhLTk2NjE5OGViNDI3OCIsImlzcyI6ImJvb3QuZGV2IiwiZXhwIjoxNzM0NDI4OTQ4LCJpYXQiOjE3MzQ0MjUzNDh9.dqCmPTx6hV1R8l5QMJ3NdUxAVhLXP3g4JihfYQ-59xw
api_url: https://api.boot.dev
base_url: https://boot.dev
color:
    gray: "8"
    green: "2"
    red: "1"
last_refresh: 1734425348
refresh_token: db0ugNOKN99Ac3NhPXdh3fix-ar3eQJc
