access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVVVJRCI6IjJkNzViNTg5LWQ0YWYtNGQ3MS1hY2FhLTk2NjE5OGViNDI3OCIsImlzcyI6ImJvb3QuZGV2IiwiZXhwIjoxNzMyMTg4Mjc2LCJpYXQiOjE3MzIxODQ2NzZ9.qvrM4OFujWqouu8Ab_hVdrHBo609xRGJCldaSCcYwpA
api_url: https://api.boot.dev
base_url: https://boot.dev
color:
    gray: "8"
    green: "2"
    red: "1"
last_refresh: 1732184676
refresh_token: gk7ObnbUr17Ign1plHlUaLqS_GDZ13vB
