github.com:
    users:
        Johnyboi77:
            oauth_token: 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
    git_protocol: https
    user: Johnyboi77
    oauth_token: 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
